### ISSUE TITLE
Permission denied to access property "addEventListener" on cross-origin object

### ISSUE THREAD

**Issue by mxk-ru** [Diokuz/baron#171] opened 2017-12-05 05:59 UTC
baron.js:103

This error only on https sites

**Comment by mxk-ru** [comment] 2017-12-05 06:03
This code is work normal

```        try {
        	elem[prefix + 'EventListener'](eventName, handler, opts)
        } catch (e) {
    	
		}
```

**Comment by Diokuz** [comment] 2017-12-06 07:30
Duplicate of https://github.com/Diokuz/baron/issues/170
but thanks!

**Comment by Diokuz** [comment] 2017-12-10 12:10
Fixed in `baron@3.0.2`

**Closed by Diokuz** 2017-12-10 12:10 UTC

**Comment by mxk-ru** [comment] 2017-12-10 12:21
Where is it?

**Comment by Diokuz** [comment] 2018-04-16 17:47
https://www.npmjs.com/package/baron )
